### PR TITLE
updated

### PR DESCRIPTION
**Pull request by Karma336**

### CODE REVIEW

**Comment by HuiYang37** [comment]
you shouldn't add anything under src/test/resources, files under this package usually are used by .java files but they are not .java files.

**Review by ardal-akbar — CHANGES_REQUESTED** [review]
Which folder would you like to keep Karma? You created 2 new folders under src/test/java

**Review by HuiYang37 — APPROVED** [review]
I made the choice for you, you can update later.

**Review by ardal-akbar — APPROVED** [review]

**Comment by Karma336** [comment]
> you shouldn't add anything under src/test/resources, files under this package usually are used by .java files but they are not .java files.

Okay,

**Pull request merged**
