### PR TITLE
Turhun test ( I added my homework about add Education and Experience Test )

### PR DESCRIPTION
**Pull request by Turhunjohn**
Could you please confirm my Merge pull request?
I added my homework about add Education and Experience Test, Delete MyAccount Test.

### CODE REVIEW

**Review by Tsai-Anthony — CHANGES_REQUESTED** [review]
be sure to write all your scripts under “ src/test/java/turhunjohn/“ which is the package you created. it seems you edited under selenium which is where murad stores his demo for the class. which is also why there was a conflict that needs to be fixed in “Add Experience” and “Add Education”

**Review by HuiYang37 — COMMENTED** [review]
selenium package is NOT yours to play with, re-create your master branch, re-merge to your own branch, then push it again

**Comment by HuiYang37** [comment]
Alright, I undid your changes, DO NOT EVER add/delete/modify the selenium package. It was a HUGE PAIN in the ass to undo any change.

**Review by HuiYang37 — APPROVED** [review]
Alright, you're good to go.

**Review by Tsai-Anthony — APPROVED** [review]
looks better. ty hui

**Review by murad-boratech — APPROVED** [review]

**Pull request merged**
