### PR TITLE
<Hui> HW0810 - Added AddExperiencePremium

### PR DESCRIPTION
**Pull request by HuiYang37**
added AddExperiencePremium.
created 11 sets of data for testing BoraTech <Add Experience> page.
9 passed and 2 failed.

### CODE REVIEW

**Review by Tsai-Anthony — APPROVED** [review]
nice job!

**Review by ardal-akbar — APPROVED** [review]
Nicely done!

**Review by helen-ahn — APPROVED** [review]
LGTM!! 
PrintFile.java with html file looks interesting!

**Review by KrystalOm — APPROVED** [review]
Thumbs up!

**Pull request merged**
