### PR TITLE
homework

### PR DESCRIPTION
**Pull request by KrystalOm**
finally here~~ please check and approve my homework (forget about boraTechLogin.java) I don't know why that came together

### CODE REVIEW

**Review by ITgirlLL — APPROVED** [review]

**Comment by ITgirlLL** [comment]
Krystal you should create a new package under your name first, then add those two classes in it.

**Review by LenaChen7 — APPROVED** [review]
LGTM ：）！！

**Review by Tsai-Anthony — APPROVED** [review]

**Review by ohwellruben — APPROVED** [review]
this is the most amazing piece of work ive ever seen

**Review by LenaChen7 — APPROVED** [review]
:)

**Pull request merged**
