### PR TITLE
Education info added

### PR DESCRIPTION
**Pull request by aliceoh324**
Hi team, I added my education info. Thanks!

### CODE REVIEW

**Review by HuiYang37 — COMMENTED** [review]
You need to to create new package under src/test/java, then create new files under that package.

**Comment by HuiYang37** [comment]
You need to delete the edu file in selenium package

**Review by HuiYang37 — APPROVED** [review]
Very good, do remember, you still have one more to do

**Review by ardal-akbar — APPROVED** [review]
Looks good!

**Review by ITgirlLL — APPROVED** [review]

**Pull request merged**
