### PR TITLE
Helen api

### PR DESCRIPTION
**Pull request by helen-ahn**
CreateNewPost :
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

GetPostPageMeta :
 java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

still working on these excpetions...

### CODE REVIEW

**Comment by HuiYang37** [comment]
In your BoraTechApis:
the method addNewPost is expected a single object type:
`public static Object addNewPost (String token, Object ob)`
but in the method body, it return a list of objects:
`List <NewPost> np = response.jsonPath().getList("", NewPost.class);`

**Review by HuiYang37 — APPROVED** [review]

**Review by ardal-akbar — DISMISSED** [review]
Looks Good!

**Comment by HuiYang37** [comment]
I see, on the BoraTech Posts Page, there are two types of API request. The [post] API request will return a single json object which can coverted into a single pojo Post class. However, it doesn't automaically update the Posts Page weblink like the add experience/education. Another API request, in this case, is a [get] API request also has the same endpoint returns a list of json objects which can be converted to a list of pojo Post class. When you have both, you can valiate if the single pojo you get from the [post] API is in the the list of pojos from the [get] API.
The second part of the task is to use selenium to add post on UI, then verify the post in API.

**Comment by helen-ahn** [comment]
> I see, on the BoraTech Posts Page, there are two types of API request. The [post] API request will return a single json object which can coverted into a single pojo Post class. However, it doesn't automaically update the Posts Page weblink like the add experience/education. Another API request, in this case, is a [get] API request also has the same endpoint returns a list of json objects which can be converted to a list of pojo Post class. When you have both, you can valiate if the single pojo you get from the [post] API is in the the list of pojos from the [get] API. The second part of the task is to use selenium to add post on UI, then verify the post in API.

Thanks for your explanation! I was unclear which two objects to compare to validate new posts. It makes sense to utilize UI automation to verify a list of pojo objects from [get] API.

**Review by Tsai-Anthony — APPROVED** [review]
nice!

**Review by HuiYang37 — DISMISSED** [review]

**Review by ardal-akbar — DISMISSED** [review]

**Comment by helen-ahn** [comment]
Still getting an error on Line 25 of GetPostPageMeta Class though lol.

**Comment by HuiYang37** [comment]
In BoraTechApis, for the PostsPage: the [get] API request doesn't need a body, think of this way: you're trying to get the entire list of all the posts (in order validate if your newly added post is in that list), typically, request.body() only accepts "body" if we're sending a json object. But you already did sent a json object when you completed the [post] API request. For the [get] API request, you don't need to send anything, what we really want is for the API to return a list of posts. Only header in the [get] API request is just the "token", there shouldn't be any request.body().

**Comment by HuiYang37** [comment]
Everything looks alright except I noticed a little mistake in your GetPostPageMeta:
In line 43-44:
`
if (actualPost.text.equals(message)) {
found = false;
}
`
the boolean found should be true; since well, you found it.

**Comment by helen-ahn** [comment]
> Everything looks alright except I noticed a little mistake in your GetPostPageMeta: In line 43-44: `if (actualPost.text.equals(message)) { found = false; }` the boolean found should be true; since well, you found it.

Thank you. You have a good eye! Just updated 'found = true', but still get a No such element exception with the following line.
             driver.findElement(By.xpath("//a[@href='/posts']")).click();

**Comment by HuiYang37** [comment]
> > Everything looks alright except I noticed a little mistake in your GetPostPageMeta: In line 43-44: `if (actualPost.text.equals(message)) { found = false; }` the boolean found should be true; since well, you found it.
> 
> Thank you. You have a good eye! Just updated 'found = true', but still get a No such element exception with the following line. driver.findElement(By.xpath("//a[@href='/posts']")).click();

I didn't notice earlier, you tried to use API login, which works with API, selenium works UI, you should hava a BoraTech class in your utilities for UI login. Like BoraTech.login(email, password);

**Comment by HuiYang37** [comment]
It looks like everything is fine now.

**Review by HuiYang37 — APPROVED** [review]

**Comment by helen-ahn** [comment]
> > > Everything looks alright except I noticed a little mistake in your GetPostPageMeta: In line 43-44: `if (actualPost.text.equals(message)) { found = false; }` the boolean found should be true; since well, you found it.
> > 
> > 
> > Thank you. You have a good eye! Just updated 'found = true', but still get a No such element exception with the following line. driver.findElement(By.xpath("//a[@href='/posts']")).click();
> 
> I didn't notice earlier, you tried to use API login, which works with API, selenium works UI, you should hava a BoraTech class in your utilities for UI login. Like BoraTech.login(email, password);

No wonder why it wasn't going thru. I just fixed that and finally getting pass!! Thanks again. I have a little better understanding concept wise now.

**Comment by HuiYang37** [comment]
Btw, you might want to let any code owner know your newly added changes are ready for review. And good job on your hard work.

**Review by Tsai-Anthony — APPROVED** [review]
nice fix!

**Pull request merged**
