### PR TITLE
Lena - Add personal details on dashboard

### PR DESCRIPTION
**Pull request by LenaChen7**
Hi, Team :) 
Please review my test moves, thank you ! 🌹

### CODE REVIEW

**Comment by ITgirlLL** [comment]
Looks good!

**Review by ITgirlLL — APPROVED** [review]

**Review by HuiYang37 — COMMENTED** [review]
Very good.

**Review by HuiYang37 — APPROVED** [review]

**Review by ardal-akbar — APPROVED** [review]
Good job!

**Comment by LenaChen7** [comment]
> Very good.

Thank you Hui !

**Pull request merged**
